# Aliases
alias bp='nohup /Users/kbrown/xtuml/BridgePoint/bridgepoint >/dev/null 2>&1'
alias bpdev='nohup /Users/kbrown/xtuml/bpdev/bridgepoint >/dev/null 2>&1'

alias ll='ls -alF'
alias la='ls -A'
alias ls='ls -CFG'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias rm='rm -ri'
alias cp='cp -ri'
alias mv='mv -i'
alias h='history'
alias vi='vim'
alias please='sudo'

alias serve='python -m SimpleHTTPServer 8080'

alias sql='mysql -u root -pkbrown'

alias git-ssh-gen='ssh-keygen -t rsa -b 4096 -C "s.keith.brown@gmail.com"'

# .dot setup aliases
alias bashrc='vim ~/.bashrc'
alias bashmac='vim ~/.bashmac'
alias bashlinux='vim ~/.bashlinux'
alias bash_aliases='vim ~/.bash_aliases'
alias profile='vim ~/.profile'
alias vimrc='vim ~/.vimrc'
alias gitconfig='vim ~/.gitconfig'
alias gitignore='vim ~/.gitignore'
alias dot='~/.dot/setup.sh'
