# Aliases
alias bp='~/bin/runbp.sh'
alias bpdev='~/bin/runbp.sh'

alias ll='ls -alF'
alias la='ls -A'
alias ls='ls -CFG'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias rm='rm -ri'
alias cp='cp -ri'
alias mv='mv -i'
alias h='history'
alias vi='vim'
alias please='sudo'

alias findbig='du -d 1 -h . 2>/dev/null | sort -rh | head -n 20'

alias serve='python -m SimpleHTTPServer 8080'

alias sql='mysql -u root -pkbrown'

# .dot setup aliases
alias bashrc='vim ~/.bashrc'
alias bashmac='vim ~/.bashmac'
alias bashlinux='vim ~/.bashlinux'
alias bash_aliases='vim ~/.bash_aliases'
alias profile='vim ~/.profile'
alias vimrc='vim ~/.vimrc'
alias gitconfig='vim ~/.gitconfig'
alias gitignore='vim ~/.gitignore'
alias dot='~/.dot/setup.sh'
